# Generated by Django 4.2 on 2024-12-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_producttecinfo_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalinformation',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='technicalinformation',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='technicalinformation',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='tecinfoname',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='tecinfoname',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='tecinfoname',
            name='name_uz',
        ),
    ]
