# Generated by Django 4.2 on 2024-12-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_colors_alter_product_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='is_top',
        ),
    ]
