# Generated by Django 4.2 on 2024-12-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productcategory_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
