# Generated by Django 4.2 on 2024-12-01 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_anonymoususer_city_region_orderproduct_city_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Telefon raqami noto'g'ri formatda. To'g'ri format +998901234567 bo'lishi kerak.", regex='^(?:\\+998|998)?[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('yangi buyurtma', 'yangi buyurtma'), ('jarayonda', 'jarayonda'), ('bekor qiligan', 'bekor qiligan'), ('tugatilgan', 'tugatilgan')], max_length=250),
        ),
    ]
