# Generated by Django 4.2 on 2024-12-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productcolor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountproduct',
            name='image',
        ),
        migrations.AddField(
            model_name='discountproduct',
            name='image_en',
            field=models.ImageField(null=True, upload_to='product/discount-product'),
        ),
        migrations.AddField(
            model_name='discountproduct',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='product/discount-product'),
        ),
        migrations.AddField(
            model_name='discountproduct',
            name='image_uz',
            field=models.ImageField(null=True, upload_to='product/discount-product'),
        ),
    ]
