# Generated by Django 4.2 on 2024-12-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_city_name_en_city_name_ru_city_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymoususer',
            name='token',
        ),
        migrations.AddField(
            model_name='anonymoususer',
            name='session',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
    ]
