# Generated by Django 4.2 on 2024-11-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adversitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='common/advertisement')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Adverstisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
    ]
