# Generated by Django 4.2 on 2024-11-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='video',
            field=models.FileField(upload_to='media/common/about-us/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='media/common/advertisement'),
        ),
    ]
