# Generated by Django 4.2 on 2025-05-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_advertisement_image_advertisement_image_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='mb_image_en',
            field=models.FileField(null=True, upload_to='media/common/advertisement/mb_image', verbose_name='mobile_image_en'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='mb_image_ru',
            field=models.FileField(null=True, upload_to='media/common/advertisement/mb_image', verbose_name='mobile_image_ru'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='mb_image_uz',
            field=models.FileField(null=True, upload_to='media/common/advertisement/mb_image', verbose_name='mobile_image_uz'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_en',
            field=models.FileField(null=True, upload_to='media/common/advertisement'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_ru',
            field=models.FileField(null=True, upload_to='media/common/advertisement'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image_uz',
            field=models.FileField(null=True, upload_to='media/common/advertisement'),
        ),
    ]
