# Generated by Django 4.2 on 2024-11-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_aboutus_video_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='video',
            field=models.FileField(upload_to='common/about-us/'),
        ),
    ]
